# This is a basic workflow to help you get started with Actions
name: Deploy-On-Push-To-Main

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]

env:
  AWS_REGION : eu-west-2

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  Terraform-Deploy:
    runs-on: ubuntu-latest
    # when an env is set the context  for iam trust policy will be "repo:<User_Org>/<Repo_Name>:environment:<Env_Name>"
    environment: demo
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE}}
          role-session-name: Platform_Portal_Terraform_GitHub
          aws-region: ${{ env.AWS_REGION }}
          role-skip-session-tagging: true
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
            # Run TF
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4
      # Run TF Init
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      # Just a demo so apply
      - name: Terraform Apply
        id: plan
        run: terraform apply -auto-approve
        continue-on-error: true
